### PR TITLE
Scaffold out "rewards points" MVC

### PR DESCRIPTION
**Pull request by Gaurav2728**
https://app.asana.com/0/1123097308227067/1200649991373288/f

### CODE REVIEW

**Comment by Gaurav2728** [comment]
Reward Points (Loyalty Points) are available under the **Users** tab/section of the Admin Panel.

Reward Points (Loyalty Points Balance)
Screenshot 2021-08-07 at 8 00 01 PM

Screenshot 2021-08-07 at 8 00 16 PM

Update Loyalty Points
Screenshot 2021-08-07 at 8 06 12 PM

Screenshot 2021-08-07 at 8 11 53 PM

Updated Points
Screenshot 2021-08-07 at 8 12 07 PM

Loyalty Points balance after update
Screenshot 2021-08-07 at 8 12 29 PM

**Comment by aaronsmulktis** [comment]
Excellent work, and thank you for the additional validation with the screenshots. I'm merging this in, but after our most recent call with the client (last Friday 7/30/21) we need to move towards using "Rewards Balance" (which is just $ cash credit).

I will make a new Asana task for this, but please wait to start, I would like to triple-confirm this change is fully understood by the client. They did initially ask for rewards "points" and this is how their existing site works:

https://polclothing.com/rewardpoints/history
"Minimum balance allowed to use is 1000 reward points ($10.00)"

I will confirm the change this week.

Thank you!!

**Comment by aaronsmulktis** [comment]
@Gaurav2728 I also see the "Affiliate" user role, is this required? or just a security mechanism to help control which users are allowed to use referral codes?

**Comment by aaronsmulktis** [comment]
Also, is running `rails g spree_loyalty_points:install` necessary along with `rake db:migrate` as per the `vinsol-spree-contrib/spree-loyalty-points` README? or is this optional?

**Comment by Gaurav2728** [comment]
@aaronsmulktis thank you for the comments, `rails g spree_loyalty_points:install` required when we add it to the first time but now I already included in the PR so we don't need to do anything. Simply run `bin/rails db:migrate` that's it.

**Pull request merged**
